
// This file has been generated by the GUI designer. Do not modify.
namespace LliureXMiniScreen
{
	public partial class MainWindow
	{
		private global::Gtk.EventBox eventbox1;
		private global::Gtk.DrawingArea MiniScreen;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LliureXMiniScreen.MainWindow
			this.Name = "LliureXMiniScreen.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MiniScreen");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "stock_zoom-shift", global::Gtk.IconSize.Menu);
			this.TypeHint = ((global::Gdk.WindowTypeHint)(6));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.BorderWidth = ((uint)(2));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Gravity = ((global::Gdk.Gravity)(7));
			// Container child LliureXMiniScreen.MainWindow.Gtk.Container+ContainerChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.MiniScreen = new global::Gtk.DrawingArea ();
			this.MiniScreen.Name = "MiniScreen";
			this.eventbox1.Add (this.MiniScreen);
			this.Add (this.eventbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
